version = 0.1

[default.deploy.parameters]
stack_name = "tweeter-server"
s3_bucket = "sam-tweeter-cs340"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = []